FROM python

RUN apt-get update && \
    apt-get install -y pandoc

RUN pip install git+https://gitlab.com/myriacore/pandoc-kroki-filter.git

ENV KROKI_SERVER=https://kroki.io

WORKDIR /pandoc

ENTRYPOINT ["pandoc", "--toc", "-M", "document-css=false", "-i", "./src/documento-arquitectura-acme-store.md", "-o", "documento-arquitectura-acme-store.html", "--filter", "pandoc-kroki", "--extract-media=build"]