FROM python:3.11

ADD https://github.com/jgm/pandoc/releases/download/3.1.2/pandoc-3.1.2-1-amd64.deb /tmp/pandoc.deb

RUN dpkg -i /tmp/pandoc.deb && \
    pip install git+https://gitlab.com/myriacore/pandoc-kroki-filter.git

WORKDIR /pandoc

ENV KROKI_SERVER "https://kroki.io"
ENV TYPE html

CMD ["./run.sh"]
